Re-sync to main
rockorager/libvaxis pull request #14
Opened 2024-03-27 15:09 UTC by 00JCIV00

Sync all changes from main into personal fork in prep for a PR.

2024-03-29 03:44 UTC, 00JCIV00 commented
De-conflicted and good to go from my end. It may require a `zig fmt` run as I don't use that in my code.

2024-04-10 19:24 UTC, rockorager commented on build.zig
Let's change this back to `main.zig`. I originally thought I wanted to change the entry point but let's keep it as main for now.

2024-04-10 19:26 UTC, rockorager commented on src/Window.zig
> +pub const Screen = @import("Screen.zig");
Let's drop this `pub`. I previously exported `Screen` via `main.zig` so this isn't needed

2024-04-10 19:27 UTC, rockorager commented on src/Window.zig
> +pub const Window = @This();
We don't need a `pub` here since this is exported whenever the file is `@import`ed

2024-04-10 19:28 UTC, rockorager commented on src/vaxis.zig
> +
Let's keep this one in `main.zig`

2024-04-10 19:29 UTC, rockorager commented on src/vaxis.zig
> -const Image = @import("Image.zig");
I think I would prefer to keep these all private at this level and only expose these via `main.zig`. If there are any missing that are needed, let's add them there (but only if actually needed so as to keep the API small)

2024-04-10 19:29 UTC, rockorager commented on src/widgets/Table.zig
> +const vaxis = @import("../vaxis.zig");
Change back to `main.zig`

2024-04-10 19:30 UTC, rockorager commented on src/widgets/TextInput.zig
> +    assert(offset <= buf.len); // provided buf was too small
Not sure how this space go there but it shouldn't there haha

2024-04-10 19:31 UTC, rockorager requested changes
Left all my comments inline! Thanks!

2024-04-12 20:16 UTC, 00JCIV00 commented
No issues with the review on my part. All changes resolved.

2024-04-13 11:44 UTC, rockorager commented
Did you push your local branch back up? I'm not seeing any updates in Github.

2024-05-13 01:25 UTC, merged

2024-05-13 01:28 UTC, rockorager commented
Thanks again for all the updates to this one!